export const content = {
  hindi: {
    title: "डैशबोर्ड",
    welcome: "स्वागत है",
    stats: {
      totalSeats: "कुल सीटें",
      occupiedSeats: "भरी हुई सीटें",
      availableSeats: "खाली सीटें",
      expiringToday: "आज समाप्त होने वाली",
    },
    buttons: {
      addStudent: "नया स्टूडेंट जोड़ें",
      bulkMessage: "सभी को मैसेज भेजें",
      settings: "सेटिंग्स",
      logout: "लॉगआउट",
      checkExpiry: "एक्सपायरी चेक करें",
    },
    studentForm: {
      title: "नया स्टूडेंट जोड़ें",
      editTitle: "स्टूडेंट की जानकारी एडिट करें",
      name: "स्टूडेंट का नाम",
      phone: "मोबाइल नंबर",
      seatNumber: "सीट नंबर",
      startDate: "शुरुआत की तारीख",
      endDate: "समाप्ति की तारीख",
      photo: "फोटो अपलोड करें",
      save: "सेव करें",
      update: "अपडेट करें",
      cancel: "रद्द करें",
    },
    bulkMessageForm: {
      title: "सभी स्टूडेंट्स को मैसेज भेजें",
      message: "मैसेज लिखें",
      send: "भेजें",
      cancel: "रद्द करें",
      placeholder: "अपना मैसेज यहाँ लिखें...",
      instructions:
        "सभी स्टूडेंट्स को एक साथ मैसेज भेजने के लिए मैसेज लिखें। आपको 3 तरीके मिलेंगे मैसेज भेजने के।",
    },
    studentList: {
      title: "स्टूडेंट्स की सूची",
      seat: "सीट",
      name: "नाम",
      phone: "फोन",
      expires: "समाप्ति",
      actions: "एक्शन",
      sendMessage: "मैसेज भेजें",
      edit: "एडिट",
      delete: "डिलीट",
    },
  },
  english: {
    title: "Dashboard",
    welcome: "Welcome",
    stats: {
      totalSeats: "Total Seats",
      occupiedSeats: "Occupied Seats",
      availableSeats: "Available Seats",
      expiringToday: "Expiring Today",
    },
    buttons: {
      addStudent: "Add New Student",
      bulkMessage: "Send Bulk Message",
      settings: "Settings",
      logout: "Logout",
      checkExpiry: "Check Expiry",
    },
    studentForm: {
      title: "Add New Student",
      editTitle: "Edit Student Information",
      name: "Student Name",
      phone: "Mobile Number",
      seatNumber: "Seat Number",
      startDate: "Start Date",
      endDate: "End Date",
      photo: "Upload Photo",
      save: "Save",
      update: "Update",
      cancel: "Cancel",
    },
    bulkMessageForm: {
      title: "Send Message to All Students",
      message: "Write Message",
      send: "Send",
      cancel: "Cancel",
      placeholder: "Write your message here...",
      instructions:
        "Write your message to send to all students. You will get 3 methods to send the message.",
    },
    studentList: {
      title: "Students List",
      seat: "Seat",
      name: "Name",
      phone: "Phone",
      expires: "Expires",
      actions: "Actions",
      sendMessage: "Send Message",
      edit: "Edit",
      delete: "Delete",
    },
  },
};
